### ISSUE TITLE
Vướng cài đặt scratch cho dmoj judge

### ISSUE THREAD

**Issue by phuleethanh** [cuom1999/ScratchCLI#1]
Mình make judge-tierlqdoj rồi, nhưng khi chạy docker thì runtime không có scratch.
Mình đã sửa dòng này trong dockerfile của tierlqdoj để git ScratchCLI vào thư mục /usr/bin/scratch:
RUN mkdir /usr/bin/scratch && cd /usr/bin/scratch && \
    curl -L https://github.com/cuom1999/ScratchCLI/archive/master.tar.gz | tar -xz --strip-components=1 
Đã thực hiện:
  + thêm ngôn ngữ mới là scratch trên site
  + get repo ScratchCLI về, đã chạy nmp install
  + thêm vào judge.yml dòng runtime: scratch: /usr/bin/scratch
Nhưng khi chạy máy chấm trên docker , quá trình self-testing nó không testing scratch.

Mong bạn giúp đỡ thêm để hoàn thiện thêm scratch vào judge để chấm scratch.
Cảm ơn

**Comment by cuom1999** [comment]
Thầy giữ nguyên file docker nhưng trong file judge.conf thì thêm 2 dòng này vào
```
  scratch: /ScratchCLI/scratch
  scat_home: /ScratchCLI
```
